dist: trusty
language: cpp
cache: ccache
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - autoconf
    - automake
    - autotools-dev
    - autopoint
    - libtool
    - pkg-config
    - libssl-dev
    - libc-ares-dev
    - libxml2-dev
    - zlib1g-dev
    - libsqlite3-dev
    - libssh2-1-dev
    - libcppunit-dev
before_install:
  - $CC --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="$CXX -Qunused-arguments" CC="$CC -Qunused-arguments"; fi
  - $CC --version
before_script:
  - autoreconf -i
  - automake
  - autoconf
  - ./configure CPPFLAGS=-fsanitize=address LDFLAGS="-fsanitize=address -fuse-ld=gold"
script:
  - make CC="ccache $CC" CXX="ccache $CXX" check
